import { hashSync } from "bcryptjs";

const userData = {
  users: [
    {
      name: "First Monie",
      email: "testemail@gmail.com",
      password: hashSync("1234567"),
      isAdmin: true,
      telephone: "08034567862",
      userName: "stanley",
      country: "France",
      sex: "male",
      occupation: "Business man",
      marital_status: "single",
      account_number: "0144389034",
      birthday: "12/10/1989",
    },
    {
      name: "Ose Chris",
      email: "osechris3@gmail.com",
      password: hashSync("osechris3"),
      isAdmin: false,
      telephone: "08034567859",
      userName: "osechris",
      country: "Sweden",
      sex: "male",
      occupation: "Business man",
      marital_status: "single",
      account_number: "0144389034",
      birthday: "12/10/1989",
    },
  ],
  transactions: [
    {
      amount: "0.01$",
      client: "osechris3@gmail.com",
      TXNID: "5gSYXYFeisZZ",
      date: "13 Nov 2022",
      type: "Deposit",
    },
    {
      amount: "9000$",
      client: "osechris3@gmail.com",
      TXNID: "MvM91668104103",
      date: "11 Nov 2022",
      type: "Dps",
    },
    {
      amount: "100000$",
      client: "osechris3@gmail.com",
      TXNID: "SqLB1667852900",
      date: "08 Nov 2022",
      type: "Fdr",
    },
    {
      amount: "20000$",
      client: "osechris3@gmail.com",
      TXNID: "QkZU1667772774",
      date: "07 Nov 2022",
      type: "Dps",
    },
    {
      amount: "10000$",
      client: "osechris3@gmail.com",
      TXNID: "qSem1667766779",
      date: "07 Nov 2022",
      type: "Dps",
    },
  ],
  loans: [
    {
      LOAN_AMOUNT: "20000$",
      PLAN_NO: "DO3H1667586117",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "M25c1664847118",
      PER_INSTALLMENT: "300$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "bJVa1664957525",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "crAv1667496538",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "30000$",
      PLAN_NO: "Mx4A1667523466",
      PER_INSTALLMENT: "900$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "50000$",
      PLAN_NO: "9h641664830304",
      PER_INSTALLMENT: "500$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "60000$",
      PLAN_NO: "LFxD1664776690",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "55",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "vBZf1664566657",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "0SWF1662049461",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "JyH21662027898",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "50000$",
      PLAN_NO: "4FjP1659328633",
      PER_INSTALLMENT: "500$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "60000$",
      PLAN_NO: "OGe91659298558",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "55",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "KXmF1656827461",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "VBuY1656717067",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "zF6R165667024",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "7kAb1656649085",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "50000$",
      PLAN_NO: "m1l11654259518",
      PER_INSTALLMENT: "500$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "60000$",
      PLAN_NO: "96801654243561",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "55",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "g9xq1654075964",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "sWlc1654075779",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "PRkv1654048896",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "JyH21662027898",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "50000$",
      PLAN_NO: "GSCx1651573582",
      PER_INSTALLMENT: "500$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "60000$",
      PLAN_NO: "If291651521852",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "55",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "TJNb1651445736",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "Xjf01651382663",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "CAGr1651365542",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "Z9ag1651355789",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "50000$",
      PLAN_NO: "TwQe1651353185",
      PER_INSTALLMENT: "500$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "60000$",
      PLAN_NO: "Uqhi1648841468",
      PER_INSTALLMENT: "600$",
      TOTAL_INSTALLEMENT: "55",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "100000$",
      PLAN_NO: "cYLF1648835139",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "10000$",
      PLAN_NO: "yMRK1648776998",
      PER_INSTALLMENT: "1000$",
      TOTAL_INSTALLEMENT: "15",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
    {
      LOAN_AMOUNT: "300000$",
      PLAN_NO: "KpXq1648775540",
      PER_INSTALLMENT: "3000$",
      TOTAL_INSTALLEMENT: "35",
      NEXT_INSTALLEMENT: "25",
      STATUS: "pending",
    },
  ],
  dps: [
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "180000$",
      matured_amount: "196200$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Bronze",
      deposit_amount: "360000$",
      matured_amount: "392400$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "180000$",
      matured_amount: "196200$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Bronze",
      deposit_amount: "360000$",
      matured_amount: "392400$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "180000$",
      matured_amount: "196200$",
      total_installment: "20",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Bronze",
      deposit_amount: "360000$",
      matured_amount: "392400$",
      total_installment: "36",
      next_installment: "",
      status: "Closed",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "180000$",
      matured_amount: "196200$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Bronze",
      deposit_amount: "360000$",
      matured_amount: "392400$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "1600$",
      matured_amount: "1920$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "180000$",
      matured_amount: "196200$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "720000$",
      matured_amount: "792000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Bronze",
      deposit_amount: "240000$",
      matured_amount: "232400$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "990000$",
      matured_amount: "992000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "380000$",
      matured_amount: "382000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Basic",
      deposit_amount: "430000$",
      matured_amount: "436200$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "220000$",
      matured_amount: "292000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Bronze",
      deposit_amount: "760000$",
      matured_amount: "792400$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "490000$",
      matured_amount: "452000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "840000$",
      matured_amount: "842000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "4600$",
      matured_amount: "4920$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "850000$",
      matured_amount: "852000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "4500$",
      matured_amount: "2520$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Premium",
      deposit_amount: "9400$",
      matured_amount: "7520$",
      total_installment: "20",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "290000$",
      matured_amount: "295000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
    {
      plan: "Gold",
      deposit_amount: "430000$",
      matured_amount: "436000$",
      total_installment: "36",
      next_installment: "",
      status: "Running",
    },
  ],
  fdr: [
    {
      plan: "Gold",
      amount: "250000$",
      profit_type: "FIXED",
      profit: "32500$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "13000$",
      status: "Closed",
    },
    {
      plan: "Basic",
      amount: "20$",
      profit_type: "FIXED",
      profit: "0.6$",
      status: "Running",
    },
    {
      plan: "Premium",
      amount: "100$",
      profit_type: "FIXED",
      profit: "32500$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "250000$",
      profit_type: "FIXED",
      profit: "4$",
      status: "Running",
    },
    {
      plan: "Basic",
      amount: "30$",
      profit_type: "FIXED",
      profit: "0.9$",
      status: "Closed",
    },
    {
      plan: "Basic",
      amount: "20$",
      profit_type: "FIXED",
      profit: "0.6$",
      status: "Closed",
    },
    {
      plan: "Basic",
      amount: "100$",
      profit_type: "FIXED",
      profit: "3$",
      status: "Closed",
    },
    {
      plan: "Basic",
      amount: "200$",
      profit_type: "FIXED",
      profit: "6$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "200000$",
      profit_type: "FIXED",
      profit: "260000$",
      status: "Running",
    },
    {
      plan: "Bronze",
      amount: "10000$",
      profit_type: "FIXED",
      profit: "1100$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "13000$",
      status: "Closed",
    },
    {
      plan: "Bronze",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "11000$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "2000000$",
      profit_type: "FIXED",
      profit: "260000$",
      status: "Closed",
    },
    {
      plan: "Gold",
      amount: "55$",
      profit_type: "FIXED",
      profit: "2.2$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "13000$",
      status: "Running",
    },
    {
      plan: "Bronze",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "11000$",
      status: "Closed",
    },
    {
      plan: "Gold",
      amount: "1000000$",
      profit_type: "FIXED",
      profit: "130000$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "10000$",
      profit_type: "FIXED",
      profit: "1100$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "500000$",
      profit_type: "FIXED",
      profit: "65000$",
      status: "Running",
    },
    {
      plan: "Basic",
      amount: "100$",
      profit_type: "FIXED",
      profit: "3$",
      status: "Closed",
    },
    {
      plan: "Bronze",
      amount: "100000$",
      profit_type: "FIXED",
      profit: "11000$",
      status: "Closed",
    },
    {
      plan: "Basic",
      amount: "100$",
      profit_type: "FIXED",
      profit: "3$",
      status: "Running",
    },
    {
      plan: "Gold",
      amount: "500000$",
      profit_type: "FIXED",
      profit: "65000$",
      status: "Running",
    },
    {
      plan: "Premium",
      amount: "65$",
      profit_type: "FIXED",
      profit: "2.6$",
      status: "Running",
    },
  ],
  withdrawals: [
    {
      date: "06-Nov-2022",
      status: "pending",
      amount: "4375.34$",
      method: "Paypal",
    },
    {
      date: "06-Nov-2022",
      status: "pending",
      amount: "41.34$",
      method: "Paypal",
    },
    {
      date: "06-Nov-2022",
      status: "pending",
      amount: "273844$",
      method: "paypal",
    },
    {
      date: "06-Nov-2022",
      status: "pending",
      amount: "29548$",
      method: "Paypal",
    },
    {
      date: "05-Nov-2022",
      status: "pending",
      amount: "131.11$",
      method: "Paypal",
    },
    {
      date: "05-Nov-2022",
      status: "pending",
      amount: "4.66$",
      method: "Paypal",
    },
    {
      date: "04-Nov-2022",
      status: "pending",
      amount: "11.31$",
      method: "Paypal",
    },
    {
      date: "01-Nov-2022",
      status: "pending",
      amount: "4.9$",
      method: "Paypal",
    },
    {
      date: "28-Oct-2022",
      status: "pending",
      amount: "7.85$",
      method: "Paypal",
    },
    {
      date: "26-Oct-2022",
      status: "pending",
      amount: "	2.93$",
      method: "Paypal",
    },
    {
      date: "24-Oct-2022",
      status: "pending",
      amount: "0.96$",
      method: "Paypal",
    },
    {
      date: "24-Oct-2022",
      status: "pending",
      amount: "2953$",
      method: "	Paypal",
    },
    {
      date: "22-Oct-2022",
      status: "pending",
      amount: "337.83$",
      method: "Paypal",
    },
    {
      date: "20-Oct-2022",
      status: "pending",
      amount: "4923$",
      method: "Paypal",
    },
    {
      date: "15-Oct-2022",
      status: "pending",
      amount: "	4923$",
      method: "Paypal",
    },
    {
      date: "15-Oct-2022",
      status: "pending",
      amount: "	17.7$",
      method: "Paypal",
    },
    {
      date: "13-Oct-2022",
      status: "pending",
      amount: "2.93$",
      method: "Paypal",
    },
    {
      date: "08-Oct-2022",
      status: "pending",
      amount: "2.93$",
      method: "Paypal",
    },
    {
      date: "29-Sep-2022",
      status: "pending",
      amount: "	96.5$",
      method: "Paypal",
    },
    {
      date: "28-Sep-2022",
      status: "pending",
      amount: "195$",
      method: "Paypal",
    },
    {
      date: "24-Sep-2022",
      status: "pending",
      amount: "7.85$",
      method: "Paypal",
    },
    {
      date: "14-Sep-2022",
      status: "pending",
      amount: "	96.5$",
      method: "Paypal",
    },
    {
      date: "14-Sep-2022",
      status: "pending",
      amount: "	7.85$",
      method: "Paypal",
    },
    {
      date: "14-Sep-2022",
      status: "pending",
      amount: "1022.4$",
      method: "Paypal",
    },
  ],
  wire: [
    {
      date: "Nov 2, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Okpo",
      account_number: "8858558555",
      amount: "30$",
      status: "pending",
    },
    {
      date: "Oct 11, 2022",
      bank_name: "The City Bank Limited",
      account_name: "jessica merries",
      account_number: "8787989878978",
      amount: "30$",
      status: "pending",
    },
    {
      date: "Sep 7, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Tyler Cole",
      account_number: "0987654321",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Sep 1, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Jerry Palmer",
      account_number: "0987654321",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Aug 2, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Thoe Mas",
      account_number: "6794798494",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Jul 8, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Michael Mayas",
      account_number: "2456457678",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Jun 3 2022",
      bank_name: "The City Bank Limited",
      account_name: "Jones Maya",
      account_number: "4446788399",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Apr 2, 2022",
      bank_name: "The City Bank Limited",
      account_name: "john james",
      account_number: "887677887",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Apr 1, 2022",
      bank_name: "The City Bank Limited",
      account_name: "James Owen",
      account_number: "564556554",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Mar 21, 2022",
      bank_name: "The City Bank Limited",
      account_name: "Anita Bulkes",
      account_number: "66161619565",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Mar 25, 2022",
      bank_name: "The City Bank Limited",
      account_name: "john nomk",
      account_number: "7654678657",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Mar 23, 2022",
      bank_name: "The City Bank Limited",
      account_name: "sarah churchill",
      account_number: "7654678657",
      amount: "50$",
      status: "pending",
    },
    {
      date: "Mar 22 2022",
      bank_name: "The City Bank Limited",
      account_name: "Anthony Gabriels",
      account_number: "22333444333",
      amount: "50$",
      status: "pending",
    },
  ],
  deposits: [
    {
      date: "14-Nov-2022",
      method: "flutterwave",
      amount: "15000$",
      status: "pending",
    },
    {
      date: "14-Nov-2022",
      method: "paypal",
      amount: "2500$",
      status: "pending",
    },
    {
      date: "13-Nov-2022",
      method: "flutterwave",
      amount: "500$",
      status: "pending",
    },
    {
      date: "13-Nov-2022",
      method: "paypal",
      amount: "10000$",
      status: "pending",
    },
    {
      date: "13-Nov-2022",
      method: "razorpay",
      amount: "0.01$",
      status: "completed",
    },
    {
      date: "13-Nov-2022",
      method: "paypal",
      amount: "1555$",
      status: "pending",
    },
    {
      date: "11-Nov-2022",
      method: "paypal",
      amount: "100$",
      status: "pending",
    },
    {
      date: `11-Nov-2022`,
      method: `	flutterwave`,
      amount: `	100$`,
      status: `completed`,
    },
    {
      date: `10-Nov-2022`,
      method: `	
flutterwave`,
      amount: `	
100$`,
      status: `completed`,
    },
    {
      date: `10-Nov-2022`,
      method: `	
flutterwave`,
      amount: `	
10$`,
      status: `completed`,
    },
    {
      date: `10-Nov-2022`,
      method: `paypal`,
      amount: `	
10$`,
      status: `completed`,
    },
    {
      date: `08-Nov-2022`,
      method: `	
paypal`,
      amount: `	
100$`,
      status: `completed`,
    },
    {
      date: `4-Apr-2022`,
      method: `Flutterwave`,
      amount: `200$`,
      status: `pending`,
    },
    {
      date: `27-Mar-2022`,
      method: `	
paypal`,
      amount: `	
34$`,
      status: `	
Pending`,
    },
    {
      date: `26-Mar-2022`,
      method: `	
paypal`,
      amount: `	
10$`,
      status: `	
Pending`,
    },
    {
      date: `25-Mar-2022`,
      method: `	
flutterwave`,
      amount: `	
290$`,
      status: `pending`,
    },
    {
      date: `23-Mar-2022`,
      method: `flutterwave`,
      amount: `	
20000$`,
      status: `pending`,
    },
    {
      date: `23-Feb-2022`,
      method: `Flutterwave`,
      amount: `	
56$`,
      status: `completed`,
    },
    {
      date: `14-Feb-2022`,
      method: `ragpay`,
      amount: `	
100$`,
      status: `completed`,
    },
    {
      date: `2-Feb-2022`,
      method: `paypal`,
      amount: `240`,
      status: `cancelled`,
    },
    {
      date: `12-Jan-2022`,
      method: `flutterwave`,
      amount: `300$`,
      status: `completed`,
    },
  ],
};
export default userData;
